export type CyjsEdgeVisualPropertyName = 
| 'width'
| 'curve-style'
| 'line-style'
| 'line-color'
| 'line-fill'
| 'line-cap'
| 'line-dash-pattern'
| 'line-dash-offset'
| 'line-gradient-stop-colors'
| 'line-gradient-stop-positions'
| 'target-arrow-shape'
| 'target-arrow-color'
| 'target-arrow-fill'
| 'target-arrow-opacity'
| 'source-arrow-shape'
| 'source-arrow-color'
| 'source-arrow-fill'
| 'source-arrow-opacity'
| 'control-point-step-size'
| 'control-point-distances'
| 'control-point-weights'
| 'segment-distances'
| 'segment-weights'
| 'loop-direction'
| 'loop-sweep'
| 'edge-distances'
| 'taxi-turn'
| 'taxi-turn-min-distance'
| 'taxi-direction'
| 'taxi-turn-distance'
| 'taxi-turn-backward-distance'
| 'taxi-turn-min-distance'
| 'taxi-direction'


export type CyjsNodeVisualPropertyName = 
| 'width'
| 'height'
| 'shape'
| 'shape-polygon-points'
| 'background-color'
| 'background-blacken'
| 'background-opacity'
| 'background-fill'
| 'background-image'
| 'background-image-opacity'
| 'background-image-crossorigin'
| 'background-image-containment'
| 'background-position-x'
| 'background-position-y'
| 'background-width-relative-to'
| 'background-height-relative-to'
| 'background-width'
| 'background-height'
| 'background-offset-x'
| 'background-offset-y'
| 'background-repeat'
| 'background-fit'

export type CyjsVisualPropertyName = CyjsNodeVisualPropertyName & CyjsEdgeVisualPropertyName