// type CyjsVisualProperty = {}

export type CyjsNodeVisualProperty = 
| 'width'
| 'height'
| 'shape'
| 'shape-polygon-points'
| 'background-color'
| 'background-blacken'
| 'background-opacity'
| 'background-fill'
| 'background-image'
| 'background-image-opacity'
| 'background-image-crossorigin'
| 'background-image-containment'
| 'background-position-x'
| 'background-position-y'
| 'background-width-relative-to'
| 'background-height-relative-to'
| 'background-width'
| 'background-height'
| 'background-offset-x'
| 'background-offset-y'
| 'background-repeat'
| 'background-fit'
