import { IdType } from '../IdType'
import { GraphObjectType } from '../NetworkModel'

export interface IndexedColumns {
  [GraphObjectType.NODE]: string[]
  [GraphObjectType.EDGE]: string[]
}

export type Operator = 'AND' | 'OR'

export interface Indices<T> {
  [GraphObjectType.NODE]: T
  [GraphObjectType.EDGE]: T
}

/**
 * Search is a generic interface for search libraries.
 *
 * T is the type of the index generated by the search library.
 * e.g. Fuse.Index, Lunr.Index, etc.
 */
export interface Search<T> {
  // Index generated by the search library
  index: Record<IdType, Indices<T>>

  // Raw query string from the user
  query: string

  // Column names to be indexed
  indexedColumns: IndexedColumns

  // Basic options for the search library
  options: SearchOptions

  // Function to convert library-specific results to a list of object IDs to be selected
  convertResults: (result: any) => IdType[]
}

// TODO: is this good enough?
export interface SearchOptions {
  exact: boolean
  operator: Operator
}
