import { IdType } from '../IdType'

/**
 * Search is a generic interface for search libraries.
 * T is the type of the index generated by the search library.
 */
export interface Search<T> {
  // Raw query string from the user
  query: string

  // Fuzzy or exact search mode
  exactMatch: boolean

  // Convert library-specific results to a list of object IDs
  toSelection: (result: any) => IdType[]

  // Index generated by the search library
  index: Record<string, T>
}
