// Third-party imports
import { Tooltip } from '@mui/material'
import * as d3Hierarchy from 'd3-hierarchy'
import * as d3Selection from 'd3-selection'
import * as d3Zoom from 'd3-zoom'
import {
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react'

// Internal component imports
import { AppConfigContext } from '../../../../AppConfigContext'
import { logUi } from '../../../../debug'
import { useCredentialStore } from '../../../../data/hooks/stores/CredentialStore'
import { useFilterStore } from '../../../../data/hooks/stores/FilterStore'
import { useRendererFunctionStore } from '../../../../data/hooks/stores/RendererFunctionStore'
import { useTableStore } from '../../../../data/hooks/stores/TableStore'
// Internal store imports
import { useViewModelStore } from '../../../../data/hooks/stores/ViewModelStore'
import { useVisualStyleStore } from '../../../../data/hooks/stores/VisualStyleStore'
import { SearchState } from '../../../../models/FilterModel/SearchState'
import { IdType } from '../../../../models/IdType'
// Internal model imports
import { Network } from '../../../../models/NetworkModel'
import { NetworkView } from '../../../../models/ViewModel'
import { VisualStyle } from '../../../../models/VisualStyleModel'
import { applyVisualStyle } from '../../../../models/VisualStyleModel/impl/visualStyleFnImpl'
import { CirclePackingView } from '../../model/CirclePackingView'
import { useSubNetworkStore } from '../../store/SubNetworkStore'
// Local imports
import {
  CirclePackingType,
  createCirclePackingView,
  createTreeLayout,
} from './CirclePackingLayout'
import {
  CpDefaults,
  displaySelectedNodes,
  findHierarchyNode,
  getColorMapper,
  getFontSize,
  getLabel,
  getWordLines,
} from './CirclePackingUtils'
import { D3TreeNode } from './D3TreeNode'

interface CirclePackingPanelProps {
  rendererId: string
  network: Network
  visible: boolean
  initialSize?: { w: number; h: number }
}

const CP_WRAPPER_CLASS = 'circle-packing-wrapper'
const SVG_ID = 'cpView'

// Color scale for the circles in the view
const colorScale = getColorMapper([0, 5])

/**
 * Circle Packing renderer as a variant of the network viewer
 *
 *
 */
export const CirclePackingPanel = ({
  rendererId,
  network,
  initialSize,
  visible,
}: CirclePackingPanelProps): JSX.Element => {
  // ===== CONTEXT =====
  const { ndexBaseUrl } = useContext(AppConfigContext)

  // ===== REFS =====
  const svgRef = useRef<SVGSVGElement>(null) // Access the SVG element generated by D3
  const zoomBehaviorRef = useRef<d3Zoom.ZoomBehavior<Element, any> | null>(null) // Keep the zoom behavior as a state
  const selectedDepthRef = useRef(0) // For keeping track of the selected node's depth in the hierarchy
  const lastZoomLevelRef = useRef(0) // Keep the last zoom level for comparison
  const updatingNetworkIdRef = useRef<IdType | null>(null) // Track which network is currently being updated
  const hasInitialFitToSelectedLeaves = useRef(false) // Track if we've done initial fit to selected leaves

  // ===== LOCAL STATE =====
  const [transform, setTransform] = useState(d3Zoom.zoomIdentity)
  const [lastNetworkId, setLastNetworkId] = useState<IdType>('')
  const [networkSwitched, setNetworkSwitched] = useState<boolean>(false)
  const [expandAll, setExpandAll] = useState<boolean>(false)
  const [selectedLeaves, setSelectedLeaves] = useState<string[]>([])
  const [tooltipOpen, setTooltipOpen] = useState<boolean>(false)
  const [tooltipContent, setTooltipContent] = useState<string>('')
  const [tooltipPosition, setTooltipPosition] = useState({ x: 0, y: 0 })
  const [hoveredEnter, setHoveredEnter] = useState<D3TreeNode>()

  // ===== STORE SELECTORS =====
  // Network and table data
  const networkId: IdType = network.id
  const tables = useTableStore((state) => state.tables)
  const { nodeTable, edgeTable } = tables[networkId] ?? {}

  // Visual styles
  const visualStyles: Record<string, VisualStyle> = useVisualStyleStore(
    (state) => state.visualStyles,
  )
  const visualStyle: VisualStyle = visualStyles[networkId]

  // View model management
  const addViewModel = useViewModelStore((state) => state.add)
  const getViewModel = useViewModelStore((state) => state.getViewModel)
  const viewModelMap: Record<IdType, NetworkView[]> = useViewModelStore(
    (state) => state.viewModels,
  )
  const views: NetworkView[] = viewModelMap[networkId] ?? []
  const exclusiveSelect = useViewModelStore((state) => state.exclusiveSelect)

  // Filter and search state
  const searchState: SearchState = useFilterStore((state) => state.search.state)

  // Renderer functions
  const getRendererFunction = useRendererFunctionStore(
    (state) => state.getFunction,
  )
  const setRendererFunction = useRendererFunctionStore(
    (state) => state.setFunction,
  )

  // Credentials and network info
  const getToken = useCredentialStore((state) => state.getToken)
  const rootNetworkId: IdType = useSubNetworkStore(
    (state) => state.rootNetworkId,
  )
  const rootNetworkHost: string = useSubNetworkStore(
    (state) => state.rootNetworkHost,
  )
  const setSelectedNodes = useSubNetworkStore((state) => state.setSelectedNodes)
  const selectedHierarchyNodeNames = useSubNetworkStore(
    (state) => state.selectedHierarchyNodeNames,
  )

  // ===== COMPUTED VALUES =====
  const rootNetworkHostUrl: string =
    rootNetworkHost === '' ? ndexBaseUrl : rootNetworkHost

  const circlePackingView: CirclePackingView | undefined = views.find(
    (view) => view.type === CirclePackingType,
  ) as CirclePackingView

  const selectedNodes: IdType[] = circlePackingView?.selectedNodes ?? []
  const selectedNodeSet = useMemo(
    () => new Set<string>(selectedNodes),
    [selectedNodes],
  )

  // ===== FUNCTIONS ====

  /**
   * Memoized event handlers to avoid re-attaching on every update
   */
  const handleCircleMouseEnter = useCallback(
    (e: any, d: d3Hierarchy.HierarchyCircularNode<D3TreeNode>) => {
      setHoveredEnter(d.data)
    },
    [],
  )

  const handleCircleClick = useCallback(
    (e: any, d: d3Hierarchy.HierarchyNode<D3TreeNode>) => {
      if (d.height !== 0) {
        // Selected item is a subsystem
        if (d.data.originalId !== undefined) {
          // Select both current and original branch
          exclusiveSelect(network.id, [d.data.originalId, d.data.id], [])
        } else {
          exclusiveSelect(network.id, [d.data.id], [])
        }

        // Clear the selection in leafs in the selected node
        setSelectedLeaves([])
        setSelectedNodes([])
      } else {
        // This is a leaf node

        // Set always one node by clicking on the leaf node
        setSelectedNodes([d.data.name])

        // Select the parent node instead
        const { parent } = d
        if (parent === null || parent === undefined) return

        const selectedChild = d.data.originalId ?? d.data.id
        setSelectedLeaves([selectedChild])

        if (parent.data.originalId !== undefined) {
          exclusiveSelect(network.id, [parent.data.originalId], [])
        } else {
          exclusiveSelect(network.id, [parent.data.id], [])
        }
      }
    },
    [network.id, exclusiveSelect, setSelectedNodes, setSelectedLeaves],
  )

  const handleCircleMouseMove = useCallback((e: any) => {
    setTooltipPosition({ x: e.clientX + 20, y: e.clientY + 20 })
  }, [])

  /**
   * Update visibility of circles and text elements based on zoom level
   */
  const updateVisibilityForZoom = (maxDepth: number): void => {
    const circles: d3Selection.Selection<
      d3Selection.BaseType,
      unknown,
      HTMLElement,
      any
    > = d3Selection.selectAll('circle')

    circles.style(
      'display',
      (d: d3Hierarchy.HierarchyNode<D3TreeNode>): string => {
        // Guard against undefined data
        if (!d || d === undefined) {
          return 'none'
        }

        // Always display all subsystems/genes if the search result is shown
        if (expandAll || d.depth === 0 || d.depth <= maxDepth) {
          return 'inline'
        } else {
          return 'none'
        }
      },
    )

    const textElements = d3Selection.selectAll('text')

    textElements.style(
      'display',
      (d: d3Hierarchy.HierarchyNode<D3TreeNode>): string => {
        // Guard against undefined data
        if (!d || d === undefined) {
          return 'none'
        }

        // Zooming logic:
        // 1. If the node is the root node, always hide the label
        // 2. If leaf node, hide the label if the zoom level is below the threshold
        // 3. If non-leaf node, show the label based on the expansion level
        const isLeaf: boolean = d.height === 0

        if (d.depth !== 0 && d.depth === maxDepth) {
          return 'inline'
        } else if (isLeaf && d.depth < maxDepth) {
          return 'inline'
        } else {
          return 'none'
        }
      },
    )
  }

  /**
   * Expand and zoom to the selected circle node
   */
  const expandSelectedCircle = (selectedNodeId: IdType) => {
    const rootNode =
      circlePackingView.hierarchy as d3Hierarchy.HierarchyCircularNode<D3TreeNode>
    const circleNode = findHierarchyNode(selectedNodeId, rootNode)
    if (circleNode === undefined) {
      logUi.warn(
        'Node selected in primary view is not found in Circle Packing view',
      )
      return
    }

    const depth: number = circleNode.depth

    selectedDepthRef.current = depth
    updateVisibilityForZoom(depth)
    lastZoomLevelRef.current = depth
  }

  /**
   * Find the parent subsystem node that contains the selected leaf nodes
   * @param leafNames - Array of leaf node names
   * @returns The parent subsystem node ID if found, undefined otherwise
   */
  const findParentSubsystemOfLeaves = (
    leafNames: string[],
  ): IdType | undefined => {
    if (
      circlePackingView === undefined ||
      circlePackingView.hierarchy === undefined ||
      leafNames.length === 0
    ) {
      return undefined
    }

    const rootNode =
      circlePackingView.hierarchy as d3Hierarchy.HierarchyCircularNode<D3TreeNode>

    // Find all leaf nodes that match the selected leaf names
    const matchingLeaves: d3Hierarchy.HierarchyCircularNode<D3TreeNode>[] = []
    rootNode.descendants().forEach((node) => {
      if (node.height === 0 && leafNames.includes(node.data.name)) {
        matchingLeaves.push(node)
      }
    })

    if (matchingLeaves.length === 0) {
      return undefined
    }

    // Find the common ancestor (subsystem) of all matching leaves
    // Start with the first leaf's parent
    const firstLeaf = matchingLeaves[0]
    if (firstLeaf.parent === null || firstLeaf.parent === undefined) {
      return undefined
    }

    let commonParent: d3Hierarchy.HierarchyCircularNode<D3TreeNode> | null =
      firstLeaf.parent

    // Check if all leaves share the same parent subsystem
    for (let i = 1; i < matchingLeaves.length; i++) {
      const leaf = matchingLeaves[i]
      if (
        leaf.parent === null ||
        leaf.parent === undefined ||
        commonParent === null
      ) {
        return undefined
      }

      // Find the lowest common ancestor by walking up both trees
      let leafParent: d3Hierarchy.HierarchyCircularNode<D3TreeNode> | null =
        leaf.parent

      // Walk up to the same depth
      while (
        commonParent !== null &&
        leafParent !== null &&
        commonParent.depth > leafParent.depth
      ) {
        commonParent = commonParent.parent
      }
      while (
        commonParent !== null &&
        leafParent !== null &&
        leafParent.depth > commonParent.depth
      ) {
        leafParent = leafParent.parent
      }

      // Now walk up both until we find the common ancestor
      while (
        commonParent !== null &&
        leafParent !== null &&
        commonParent !== leafParent
      ) {
        commonParent = commonParent.parent
        leafParent = leafParent.parent
      }
    }

    if (commonParent === null || commonParent === undefined) {
      return undefined
    }

    // Return the subsystem node ID (use originalId if available)
    return commonParent.data.originalId ?? commonParent.data.id
  }

  /**
   * Build or update the circle packing view model
   */
  const buildCirclePackingViewModel = (): void => {
    // Prevent multiple simultaneous calls
    if (
      network === undefined ||
      nodeTable === undefined ||
      visualStyle === undefined
    )
      return
    const primaryView = getViewModel(networkId)

    // Primary view is not ready yet.
    if (primaryView === undefined) return

    let rootNode: d3Hierarchy.HierarchyNode<D3TreeNode> =
      circlePackingView?.hierarchy as d3Hierarchy.HierarchyNode<D3TreeNode>

    createTreeLayout({
      network,
      nodeTable,
      rootNetworkHostUrl,
      getToken,
      rootNetworkId,
    }).then((root) => {
      rootNode = root
      if (rootNode && Object.keys(rootNode).length === 0) return

      const updatedView = applyVisualStyle({
        network: network,
        visualStyle: visualStyle,
        nodeTable: nodeTable,
        edgeTable: edgeTable,
        networkView: primaryView,
      })

      // Create a new Circle Packing view model
      const width = initialSize?.w ?? 0
      const height = initialSize?.h ?? 0
      const cpViewModel: CirclePackingView = createCirclePackingView(
        updatedView,
        rootNode,
        width,
        height,
      )

      // Register the new view model
      addViewModel(network.id, cpViewModel)
    })
  }

  // ===== EFFECTS ====

  /**
   * Handle visibility changes and initialize the view
   */
  useEffect(
    function onVisibilityChange() {
      if (!visible) return

      // Don't auto-expand on visibility change - only expand on initial load with selected leaves from URL
      // The expansion is handled in onSelectedHierarchyNodeNamesChange when selected leaves are present

      /**
       * Initialize and register the fit function for the circle packing renderer
       */
      const fitFunction = getRendererFunction(rendererId, 'fit')

      /**
       * Fit the circle packing visualization to the viewport
       */
      const fitCircleToViewport = () => {
        if (svgRef.current === null) return

        const { width, height } = svgRef.current.getBoundingClientRect()
        const parentWidth = width
        const parentHeight = height

        const wrapper = d3Selection.select(
          `g.${CP_WRAPPER_CLASS}`,
        ) as d3Selection.Selection<Element, any, any, any>
        if (wrapper === null) return

        const node = wrapper.node() as SVGGraphicsElement
        if (node === null) return

        const bbox = node.getBBox()
        const wrapperWidth = bbox.width
        const wrapperHeight = bbox.height
        const deltaX: number = bbox.x
        const deltaY: number = bbox.y

        const scaleX = parentWidth / wrapperWidth
        const scaleY = parentHeight / wrapperHeight
        const scale = Math.min(scaleX, scaleY) // Fit to the smaller dimension

        const scaledWidth = wrapperWidth * scale
        const scaledHeight = wrapperHeight * scale

        const translateX = (parentWidth - scaledWidth) / 2 - deltaX * scale
        const translateY = (parentHeight - scaledHeight) / 2 - deltaY * scale

        const newTransform = d3Zoom.zoomIdentity
          .translate(translateX, translateY)
          .scale(scale)

        if (zoomBehaviorRef.current == null) return

        setTransform(newTransform)
        zoomBehaviorRef.current.transform(wrapper, newTransform)
      }
      if (fitFunction === undefined) {
        setRendererFunction(rendererId, 'fit', fitCircleToViewport)
      }
      if (initialSize !== undefined && initialSize.w > 0 && initialSize.h > 0) {
        fitCircleToViewport()
      }

      setNetworkSwitched(true)
    },
    [visible],
  )

  /**
   * Apply transform changes to the zoom behavior
   */
  useEffect(
    function onTransformChange() {
      if (zoomBehaviorRef.current !== null && svgRef.current !== null) {
        const selection = d3Selection.select(svgRef.current)
        selection.call(zoomBehaviorRef.current.transform, d3Zoom.zoomIdentity)
        zoomBehaviorRef.current.transform(selection, transform)
      }
    },
    [transform],
  )

  /**
   * Update visibility when expand all state changes
   */
  useEffect(
    function onExpandAllChange() {
      updateVisibilityForZoom(lastZoomLevelRef.current)
    },
    [expandAll],
  )

  /**
   * Handle search state changes and update expansion
   */
  useEffect(
    function onSearchStateChange() {
      if (searchState === SearchState.DONE) {
        setExpandAll(true)
      } else {
        setExpandAll(false)
      }
      updateVisibilityForZoom(lastZoomLevelRef.current)
    },
    [searchState],
  )

  /**
   * Initialize zoom behavior for the SVG
   */
  useEffect(function onMount() {
    if (svgRef.current === null) return
    if (zoomBehaviorRef.current !== null) {
      return
    }
    /**
     * Handle zoom events and update visibility based on zoom level
     */
    const zoomBehavior: d3Zoom.ZoomBehavior<Element, any> = d3Zoom
      .zoom()
      .scaleExtent([0.1, 40])
      .on('zoom', (e: any): void => {
        const selectedArea = d3Selection.select(`g.${CP_WRAPPER_CLASS}`)
        selectedArea.attr('transform', e.transform)
        const currentZoomLevel = e.transform.k
        const maxDepth = Math.ceil(currentZoomLevel)

        if (selectedDepthRef.current > maxDepth) {
          lastZoomLevelRef.current = selectedDepthRef.current
        } else {
          lastZoomLevelRef.current = maxDepth
          updateVisibilityForZoom(maxDepth)
        }
      })

    // Share zoom behavior as a state
    zoomBehaviorRef.current = zoomBehavior
    d3Selection.select(svgRef.current).call(zoomBehaviorRef.current)

    return () => {
      if (svgRef.current) {
        // const svg = d3Selection.select(svgRef.current)
        // // Remove all event listeners (click, zoom, mouseenter, mousemove)
        // svg.on('click', null)
        // svg.on('zoom', null)
        // // Remove all SVG content (circles, text, groups)
        // svg.selectAll('*').remove()
        // // Clear refs to prevent memory leaks
        // zoomBehaviorRef.current = null
      }
    }
  }, [])

  /**
   * Update selected leaf when hierarchy node names change
   * This syncs selections in the subnetwork view to this circle packing view
   */
  useEffect(
    function onSelectedHierarchyNodeNamesChange() {
      // Sync selections from the subnetwork view to the circle packing view
      if (selectedHierarchyNodeNames.length === 0) {
        setSelectedLeaves([])
        displaySelectedNodes(selectedNodeSet, [])
        hasInitialFitToSelectedLeaves.current = false
      } else {
        setSelectedLeaves(selectedHierarchyNodeNames)
        displaySelectedNodes(selectedNodeSet, selectedHierarchyNodeNames)

        // On initial load with selected leaves, expand to the subsystem containing them
        if (!hasInitialFitToSelectedLeaves.current && visible) {
          hasInitialFitToSelectedLeaves.current = true

          // Determine which subsystem to expand to
          let subsystemToExpand: IdType | undefined

          // First, check if there's already a selected subsystem
          if (selectedNodes.length > 0) {
            subsystemToExpand = selectedNodes[0]
          } else {
            // Find the parent subsystem of the selected leaves
            subsystemToExpand = findParentSubsystemOfLeaves(
              selectedHierarchyNodeNames,
            )

            // If found, select it so it expands
            if (subsystemToExpand !== undefined) {
              exclusiveSelect(network.id, [subsystemToExpand], [])
            }
          }

          // Expand to the subsystem after a short delay to ensure rendering is complete
          if (
            subsystemToExpand !== undefined &&
            circlePackingView !== undefined &&
            circlePackingView.hierarchy !== undefined
          ) {
            setTimeout(() => {
              expandSelectedCircle(subsystemToExpand!)
              // Also fit the viewport to show the selected subsystem
              if (svgRef.current !== null && zoomBehaviorRef.current !== null) {
                const wrapper = d3Selection.select(`g.${CP_WRAPPER_CLASS}`)
                if (wrapper.node() !== null) {
                  const subsystemNode = findHierarchyNode(
                    subsystemToExpand!,
                    circlePackingView.hierarchy as d3Hierarchy.HierarchyCircularNode<D3TreeNode>,
                  )
                  if (subsystemNode !== undefined) {
                    const { width, height } =
                      svgRef.current.getBoundingClientRect()
                    const scale =
                      Math.min(
                        width / (subsystemNode.r * 2),
                        height / (subsystemNode.r * 2),
                      ) * 0.5 // 0.5 for padding (zoom out more)
                    const translateX = width / 2 - subsystemNode.x * scale
                    const translateY = height / 2 - subsystemNode.y * scale
                    const newTransform = d3Zoom.zoomIdentity
                      .translate(translateX, translateY)
                      .scale(scale)
                    setTransform(newTransform)
                    const wrapperNode = wrapper.node() as Element
                    if (
                      wrapperNode !== null &&
                      zoomBehaviorRef.current !== null
                    ) {
                      zoomBehaviorRef.current.transform(
                        d3Selection.select(
                          wrapperNode,
                        ) as d3Selection.Selection<Element, any, any, any>,
                        newTransform,
                      )
                    }
                  }
                }
              }
            }, 500)
          }
        }
      }
    },
    [selectedHierarchyNodeNames],
  )

  /**
   * Draw the circle packing visualization
   */
  const drawCirclePacking = (
    rootNode: d3Hierarchy.HierarchyNode<D3TreeNode>,
  ): void => {
    // Pick the base tag
    const svg: any = d3Selection.select(svgRef.current)
    svg.selectAll('*').remove()

    const wrapper = svg.append('g').attr('class', CP_WRAPPER_CLASS)

    // Handle background click to clear selections
    svg.on('click', (event: any) => {
      if (event.target.id === SVG_ID) {
        // Clear the selection in interaction network
        setSelectedNodes([])

        // Clear the selection in the CP view's leaf node
        setSelectedLeaves([])

        // Clear the selection of a circle in the CP view
        exclusiveSelect(network.id, [], [])

        // Redraw the CP view
        displaySelectedNodes(new Set<string>(), [])
        logUi.info(
          `[${drawCirclePacking.name}]: Selection in CP cleared: ${selectedNodes.length}`,
        )
      }
    })

    wrapper
      .append('g')
      .selectAll('circle')
      .data(rootNode.descendants())
      .join('circle')
      .attr('cx', (d: d3Hierarchy.HierarchyCircularNode<any>) => d.x)
      .attr('cy', (d: d3Hierarchy.HierarchyCircularNode<any>) => d.y)
      .attr('r', (d: d3Hierarchy.HierarchyCircularNode<any>) => d.r)
      .attr('stroke', (d: d3Hierarchy.HierarchyCircularNode<any>) =>
        selectedNodeSet.has(d.data.id)
          ? CpDefaults.selectedBorderColor
          : CpDefaults.borderColor,
      )
      .attr('stroke-width', (d: d3Hierarchy.HierarchyCircularNode<any>) => {
        // return d.data.id === selected || d.data.originalId === selected
        return selectedNodeSet.has(d.data.id) ||
          selectedNodeSet.has(d.data.originalId)
          ? CpDefaults.borderWidthHover
          : CpDefaults.borderWidth
      })
      .attr('fill', (d: d3Hierarchy.HierarchyNode<D3TreeNode>) => {
        return colorScale(d.depth)
      })
      .on('mouseenter', handleCircleMouseEnter)
      .on('click', handleCircleClick)
      .on('mousemove', handleCircleMouseMove)

    // Add the text labels
    wrapper
      .append('g')
      .selectAll('text')
      .data(rootNode.descendants())
      .join('text')
      .each(function (d: d3Hierarchy.HierarchyCircularNode<D3TreeNode>) {
        // Add the label on top of the circle
        const label: string = getLabel(
          d.data.id,
          circlePackingView,
          d.data.name,
        )
        const fontSize = getFontSize(d, label)
        const newStrings: string[] = getWordLines(label)
        const textHeight: number = newStrings.length * fontSize

        newStrings.forEach((word: string, lineNumber: number) => {
          const element = d3Selection.select(this)
          const y: number =
            d.y + lineNumber * fontSize - textHeight / 2 + fontSize / 2
          addTextLabels(element, word, fontSize, d.x, y)
        })
      })
      .style('display', (d: d3Hierarchy.HierarchyNode<D3TreeNode>): string => {
        const isLeaf: boolean = d.height === 0
        const isRoot: boolean = d.depth === 0
        return isLeaf || isRoot ? 'none' : 'inline'
      })

    updateVisibilityForZoom(1)
  }

  /**
   * Add text labels to circle packing elements
   */
  const addTextLabels = (
    element: any,
    word: string,
    fontSize: number,
    x: number,
    y: number,
  ) => {
    element
      .append('tspan')
      .text(word)
      .attr('font-size', fontSize)
      .attr('text-anchor', 'middle')
      .attr('alignment-baseline', 'middle')
      .attr('text-align', 'center')
      .attr('x', x)
      .attr('y', y)
      .style('user-select', 'none')
  }

  /**
   * Redraw the circle packing layout when the view model has been updated
   */
  useEffect(
    function onVisualStyleChange() {
      if (circlePackingView === undefined) return

      try {
        buildCirclePackingViewModel()
      } catch (e) {
        logUi.error(
          `[${buildCirclePackingViewModel.name}]: Failed to build the Circle Packing view`,
          e,
        )
        throw e
      }
    },
    [visualStyle],
  )

  /**
   * Handle circle packing view updates and redraw when needed
   */
  useEffect(
    function onCirclePackingViewChange() {
      if (
        circlePackingView === undefined ||
        circlePackingView.hierarchy === undefined
      )
        return

      // Prevent concurrent updates for the same network
      // Allow updates if network changed (force update)
      if (
        updatingNetworkIdRef.current === networkId &&
        networkId === lastNetworkId
      ) {
        return // Skip if already updating the same network
      }
      updatingNetworkIdRef.current = networkId

      const rootNode: d3Hierarchy.HierarchyNode<D3TreeNode> =
        circlePackingView.hierarchy as d3Hierarchy.HierarchyNode<D3TreeNode>

      // Check if wrapper exists - if not, we need to redraw
      const wrapperExists =
        d3Selection.select(`.${CP_WRAPPER_CLASS}`).node() !== null

      if (networkId !== lastNetworkId || !wrapperExists) {
        // Network changed or wrapper missing → full redraw
        drawCirclePacking(rootNode)
        setLastNetworkId(networkId)
        updatingNetworkIdRef.current = null
      } else {
        // Same network, wrapper exists → update (e.g., when visual style changes)
        // But we need to ensure circles are properly updated with colors
        const wrapper = d3Selection.select(`.${CP_WRAPPER_CLASS}`)

        // Get or create the circles container <g> (first child)
        let circlesGroup = wrapper.select('g:first-child')
        if (circlesGroup.empty()) {
          circlesGroup = wrapper.append('g')
        }

        // Use D3's join pattern which is optimized for updates
        // It will only update existing elements, enter new ones, and exit removed ones
        const circles = circlesGroup
          .selectAll('circle')
          .data(rootNode.descendants(), (d: any) => d.data.id)

        // Update existing circles - only update attributes that might have changed
        circles
          .attr('cx', (d: d3Hierarchy.HierarchyCircularNode<any>) => d.x)
          .attr('cy', (d: d3Hierarchy.HierarchyCircularNode<any>) => d.y)
          .attr('r', (d: d3Hierarchy.HierarchyCircularNode<any>) => d.r)
          .attr('fill', (d: d3Hierarchy.HierarchyNode<D3TreeNode>) => {
            return colorScale(d.depth)
          })
          .attr('stroke', (d: d3Hierarchy.HierarchyCircularNode<any>) =>
            selectedNodeSet.has(d.data.id)
              ? CpDefaults.selectedBorderColor
              : CpDefaults.borderColor,
          )
          .attr('stroke-width', (d: d3Hierarchy.HierarchyCircularNode<any>) => {
            return selectedNodeSet.has(d.data.id) ||
              selectedNodeSet.has(d.data.originalId)
              ? CpDefaults.borderWidthHover
              : CpDefaults.borderWidth
          })

        // Enter new circles (with all attributes and handlers)
        circles
          .enter()
          .append('circle')
          .attr('cx', (d: d3Hierarchy.HierarchyCircularNode<any>) => d.x)
          .attr('cy', (d: d3Hierarchy.HierarchyCircularNode<any>) => d.y)
          .attr('r', (d: d3Hierarchy.HierarchyCircularNode<any>) => d.r)
          .attr('fill', (d: d3Hierarchy.HierarchyNode<D3TreeNode>) => {
            return colorScale(d.depth)
          })
          .attr('stroke', (d: d3Hierarchy.HierarchyCircularNode<any>) =>
            selectedNodeSet.has(d.data.id)
              ? CpDefaults.selectedBorderColor
              : CpDefaults.borderColor,
          )
          .attr('stroke-width', (d: d3Hierarchy.HierarchyCircularNode<any>) => {
            return selectedNodeSet.has(d.data.id) ||
              selectedNodeSet.has(d.data.originalId)
              ? CpDefaults.borderWidthHover
              : CpDefaults.borderWidth
          })
          .on('mouseenter', handleCircleMouseEnter)
          .on('click', handleCircleClick)
          .on('mousemove', handleCircleMouseMove)

        // Remove old circles
        circles.exit().remove()

        // Only attach handlers to new circles (existing ones keep their handlers)
        // Note: D3 doesn't automatically update handlers, so we only set them on enter

        // Get or create the text container <g>
        let textGroup = wrapper.select('g:nth-child(2)')
        if (textGroup.empty()) {
          textGroup = wrapper.append('g')
        }

        // Update text labels
        textGroup
          .selectAll('text')
          .data(rootNode.descendants())
          .join('text')
          .each(function (d: d3Hierarchy.HierarchyCircularNode<D3TreeNode>) {
            const textSelection = d3Selection.select(this)
            textSelection.selectAll('*').remove()

            // Add the label on top of the circle
            const label: string = getLabel(
              d.data.id,
              circlePackingView,
              d.data.name,
            )
            const fontSize = getFontSize(d, label)
            const newStrings: string[] = getWordLines(label)
            const textHeight: number = newStrings.length * fontSize

            newStrings.forEach((word: string, lineNumber: number) => {
              const element = d3Selection.select(this)
              const y: number =
                d.y + lineNumber * fontSize - textHeight / 2 + fontSize / 2
              addTextLabels(element, word, fontSize, d.x, y)
            })
          })

        updatingNetworkIdRef.current = null
      }
    },
    // Only depend on hierarchy changes and network changes, not on selection changes
    [circlePackingView?.hierarchy, networkId, lastNetworkId],
  )

  /**
   * Handle tooltip display for hovered elements
   */
  useEffect(
    function onHoveredEnter() {
      if (hoveredEnter === undefined) {
        setTooltipOpen(false)
        return
      }

      const label: string = getLabel(
        hoveredEnter.id,
        circlePackingView,
        hoveredEnter.name,
      )
      setTooltipContent(label)
      setTooltipOpen(true)
      const timeoutId = setTimeout(() => {
        setTooltipOpen(false)
      }, 3000)

      // Clear the timeout when the component unmounts
      return () => {
        clearTimeout(timeoutId)
      }
    },
    [hoveredEnter],
  )

  /**
   * Update the stroke color of the circles based on whether their node is selected
   */
  useEffect(
    function onNodeSelection() {
      displaySelectedNodes(selectedNodeSet, selectedLeaves)

      // Don't auto-expand on node selection - only expand on initial load with selected leaves from URL
      // The expansion is handled in onSelectedHierarchyNodeNamesChange when selected leaves are present
      // Clear the networkSwitched flag so it doesn't interfere
      if (networkSwitched) {
        setNetworkSwitched(false)
      }
    },
    [selectedNodes, selectedLeaves],
  )

  /**
   * Initialize view model when initial size is available
   */
  useEffect(
    function onInitialSizeChange() {
      if (initialSize !== undefined && initialSize.w > 0 && initialSize.h > 0) {
        buildCirclePackingViewModel()
      }
    },
    [initialSize],
  )

  return (
    <>
      <svg
        id={SVG_ID}
        data-testid="circle-packing-svg"
        ref={svgRef}
        width={'100%'}
        height={'100%'}
      />
      <Tooltip
        open={tooltipOpen}
        title={tooltipContent}
        style={{
          position: 'fixed',
          top: tooltipPosition.y,
          left: tooltipPosition.x,
        }}
      >
        <div />
      </Tooltip>
    </>
  )
}
