import { VisualStyle } from '../VisualStyle'

export const defaultVisualStyle: VisualStyle = {
  nodeShape: {
    group: 'node',
    name: 'nodeShape',
    type: 'nodeShape',
    displayName: 'Shape',
    defaultValue: 'ellipse',
    mapping: null,
    bypassMap: new Map(),
  },
  nodeBorderColor: {
    group: 'node',
    name: 'nodeBorderColor',
    displayName: 'Border Color',
    type: 'color',
    defaultValue: '#000000',
    mapping: null,
    bypassMap: new Map(),
  },
  nodeBorderLineType: {
    group: 'node',
    name: 'nodeBorderLineType',
    displayName: 'Border Line',
    type: 'nodeBorderLine',
    defaultValue: 'solid',
    mapping: null,
    bypassMap: new Map(),
  },
  nodeBorderWidth: {
    group: 'node',
    name: 'nodeBorderWidth',
    displayName: 'Border Width',
    type: 'number',
    defaultValue: 1,
    mapping: null,
    bypassMap: new Map(),
  },
  nodeBorderOpacity: {
    group: 'node',
    name: 'nodeBorderOpacity',
    displayName: 'Border Opacity',
    type: 'number',
    defaultValue: 1.0,
    mapping: null,
    bypassMap: new Map(),
  },
  nodeHeight: {
    group: 'node',
    name: 'nodeHeight',
    displayName: 'Height',
    type: 'number',
    defaultValue: 40,
    mapping: null,
    bypassMap: new Map(),
  },
  nodeWidth: {
    group: 'node',
    name: 'nodeWidth',
    displayName: 'Width',
    type: 'number',
    defaultValue: 40,
    mapping: null,
    bypassMap: new Map(),
  },
  nodeBackgroundColor: {
    group: 'node',
    name: 'nodeBackgroundColor',
    displayName: 'Background Color',
    type: 'color',
    defaultValue: '#FFFFFF',
    mapping: null,
    bypassMap: new Map(),
  },
  nodeLabel: {
    group: 'node',
    name: 'nodeLabel',
    displayName: 'Label',
    type: 'string',
    defaultValue: '',
    mapping: null,
    bypassMap: new Map(),
  },
  nodeLabelColor: {
    group: 'node',
    name: 'nodeLabelColor',
    displayName: 'Label Color',
    type: 'color',
    defaultValue: '#000000',
    mapping: null,
    bypassMap: new Map(),
  },
  nodeLabelFontSize: {
    group: 'node',
    name: 'nodeLabelFontSize',
    displayName: 'Label Font Size',
    type: 'number',
    defaultValue: 12,
    mapping: null,
    bypassMap: new Map(),
  },
  nodeLabelFont: {
    group: 'node',
    name: 'nodeLabelFont',
    displayName: 'Label Font',
    type: 'font',
    defaultValue: 'serif',
    mapping: null,
    bypassMap: new Map(),
  },
  nodeLabelHorizontalAlign: {
    group: 'node',
    name: 'nodeLabelHorizontalAlign',
    displayName: 'Label Horizontal Align',
    type: 'horizontalAlign',
    defaultValue: 'center',
    mapping: null,
    bypassMap: new Map(),
  },
  nodeLabelVerticalAlign: {
    group: 'node',
    name: 'nodeLabelVerticalAlign',
    displayName: 'Label Vertical Align',
    type: 'verticalAlign',
    defaultValue: 'center',
    mapping: null,
    bypassMap: new Map(),
  },
  nodeLabelRotation: {
    group: 'node',
    name: 'nodeLabelRotation',
    displayName: 'Label Rotation',
    type: 'number',
    defaultValue: 0,
    mapping: null,
    bypassMap: new Map(),
  },
  nodeLabelOpacity: {
    group: 'node',
    name: 'nodeLabelOpacity',
    displayName: 'Label Opacity',
    type: 'number',
    defaultValue: 1.0,
    mapping: null,
    bypassMap: new Map(),
  },
  nodePositionX: {
    group: 'node',
    name: 'nodePositionX',
    displayName: 'Position X',
    type: 'number',
    defaultValue: 0,
    mapping: null,
    bypassMap: new Map(),
  },
  nodePositionY: {
    group: 'node',
    name: 'nodePositionY',
    displayName: 'Position Y',
    type: 'number',
    defaultValue: 0,
    mapping: null,
    bypassMap: new Map(),
  },
  nodePositionZ: {
    group: 'node',
    name: 'nodePositionZ',
    displayName: 'Position Z',
    type: 'number',
    defaultValue: 0,
    mapping: null,
    bypassMap: new Map(),
  },
  nodeOpacity: {
    group: 'node',
    name: 'nodeOpacity',
    displayName: 'Opacity',
    type: 'number',
    defaultValue: 1.0,
    mapping: null,
    bypassMap: new Map(),
  },
  nodeVisibility: {
    group: 'node',
    name: 'nodeVisibility',
    displayName: 'Visibility',
    type: 'visibility',
    defaultValue: 'element',
    mapping: null,
    bypassMap: new Map(),
  },
  edgeLineColor: {
    group: 'edge',
    name: 'edgeLineColor',
    displayName: 'Line Color',
    type: 'color',
    defaultValue: '#000000',
    mapping: null,
    bypassMap: new Map(),
  },
  edgeLineType: {
    group: 'edge',
    name: 'edgeLineType',
    displayName: 'Line Type',
    type: 'edgeLine',
    defaultValue: 'solid',
    mapping: null,
    bypassMap: new Map(),
  },
  edgeOpacity: {
    group: 'edge',
    name: 'edgeOpacity',
    displayName: 'Opacity',
    type: 'number',
    defaultValue: 1.0,
    mapping: null,
    bypassMap: new Map(),
  },
  edgeSourceArrowColor: {
    group: 'edge',
    name: 'edgeSourceArrowColor',
    displayName: 'Source Arrow Color',
    type: 'color',
    defaultValue: '#000000',
    mapping: null,
    bypassMap: new Map(),
  },
  edgeSourceArrowShape: {
    group: 'edge',
    name: 'edgeSourceArrowShape',
    displayName: 'Source Arrow Shape',
    type: 'edgeArrowShape',
    defaultValue: 'none',
    mapping: null,
    bypassMap: new Map(),
  },
  edgeTargetArrowColor: {
    group: 'edge',
    name: 'edgeTargetArrowColor',
    displayName: 'Target Arrow Color',
    type: 'color',
    defaultValue: '#000000',
    mapping: null,
    bypassMap: new Map(),
  },
  edgeTargetArrowShape: {
    group: 'edge',
    name: 'edgeTargetArrowShape',
    displayName: 'Target Arrow Shape',
    type: 'edgeArrowShape',
    defaultValue: 'none',
    mapping: null,
    bypassMap: new Map(),
  },
  edgeLabel: {
    group: 'edge',
    name: 'edgeLabel',
    displayName: 'Label',
    type: 'string',
    defaultValue: '',
    mapping: null,
    bypassMap: new Map(),
  },
  edgeLabelColor: {
    group: 'edge',
    name: 'edgeLabelColor',
    displayName: 'Label Color',
    type: 'color',
    defaultValue: '#000000',
    mapping: null,
    bypassMap: new Map(),
  },
  edgeLabelFontSize: {
    group: 'edge',
    name: 'edgeLabelFontSize',
    displayName: 'Label Font Size',
    type: 'number',
    defaultValue: 12,
    mapping: null,
    bypassMap: new Map(),
  },
  edgeLabelFont: {
    group: 'edge',
    name: 'edgeLabelFont',
    displayName: 'Label Font',
    type: 'font',
    defaultValue: 'serif',
    mapping: null,
    bypassMap: new Map(),
  },
  edgeLabelRotation: {
    group: 'edge',
    name: 'edgeLabelRotation',
    displayName: 'Label Rotation',
    type: 'number',
    defaultValue: 0,
    mapping: null,
    bypassMap: new Map(),
  },
  edgeLabelOpacity: {
    group: 'edge',
    name: 'edgeLabelOpacity',
    displayName: 'Label Opacity',
    defaultValue: 1.0,
    type: 'number',
    mapping: null,
    bypassMap: new Map(),
  },
  edgeLabelAutoRotation: {
    group: 'edge',
    name: 'edgeLabelAutoRotation',
    displayName: 'Label Auto Rotation',
    defaultValue: true,
    type: 'boolean',
    mapping: null,
    bypassMap: new Map(),
  },
  edgeWidth: {
    group: 'edge',
    name: 'edgeWidth',
    displayName: 'Width',
    type: 'number',
    defaultValue: 1,
    mapping: null,
    bypassMap: new Map(),
  },
  edgeVisibility: {
    group: 'edge',
    name: 'edgeVisibility',
    displayName: 'Visibility',
    type: 'visibility',
    defaultValue: 'element',
    mapping: null,
    bypassMap: new Map(),
  },
  networkBackgroundColor: {
    group: 'network',
    name: 'networkBackgroundColor',
    type: 'color',
    displayName: 'Background Color',
    defaultValue: '#FFFFFF',
    mapping: null,
    bypassMap: new Map(),
  },
}
